apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nest
  labels:
    app: nest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nest
  template:
    metadata:
      labels:
        app: nest
    spec:
      containers:
      - name: backend-nest
        imagePullPolicy: IfNotPresent
        image: jeffqev/ci-nest:main
---
apiVersion: v1
kind: Service
metadata:
  name: backend-nest
  labels:
    app: nest
spec:
  type: NodePort
  selector:
    app: nest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000